sudo: required
services:
  - docker

before_install:
  - docker build -t dilipgavara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dilipgavara/docker-react npm run test -- --coverage
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECTRET_KEY

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-319919039282"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECTRET_KEY

      